CREATE TABLE IF NOT EXISTS users (
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	email VARCHAR(255) NOT NULL,
	password VARCHAR(32) NOT NULL,
	address VARCHAR(255),
	phone VARCHAR(255),
	is_admin BOOLEAN NOT NULL DEFAULT 0,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated DATETIME ON UPDATE CURRENT_TIMESTAMP
);